// Client-side PDF receipt generator (jsPDF). Used from invoice detail page and
// the hosted checkout confirmation screen.
import { jsPDF } from "jspdf";

export type ReceiptData = {
  invoiceNumber: string;
  amount: number;
  currency: string;
  status: string;
  customerName?: string | null;
  customerEmail?: string | null;
  description?: string | null;
  methodType?: string | null;
  paidAt?: string | null;
  createdAt?: string | null;
  businessName?: string | null;
  supportEmail?: string | null;
  feeAmount?: number | null;
  netAmount?: number | null;
};

export function downloadReceipt(d: ReceiptData) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const w = doc.internal.pageSize.getWidth();
  let y = 60;

  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, w, 8, "F");

  doc.setFont("helvetica", "bold").setFontSize(22);
  doc.text(d.businessName || "PayNOC", 40, y);
  doc.setFont("helvetica", "normal").setFontSize(10).setTextColor(120);
  doc.text("Payment receipt", 40, y + 18);
  doc.setTextColor(30);

  y += 60;
  doc.setDrawColor(230).line(40, y, w - 40, y);
  y += 24;

  const row = (label: string, value: string) => {
    doc.setFont("helvetica", "normal").setFontSize(10).setTextColor(120);
    doc.text(label, 40, y);
    doc.setFont("helvetica", "bold").setFontSize(11).setTextColor(20);
    doc.text(value, 200, y);
    y += 22;
  };

  row("Invoice", d.invoiceNumber);
  row("Status", d.status.toUpperCase());
  row("Amount", `${d.currency} ${Number(d.amount).toLocaleString()}`);
  if (d.methodType) row("Method", d.methodType.toUpperCase());
  if (d.customerName) row("Customer", d.customerName);
  if (d.customerEmail) row("Email", d.customerEmail);
  if (d.description) row("Description", d.description);
  if (d.createdAt) row("Created", new Date(d.createdAt).toLocaleString());
  if (d.paidAt) row("Paid", new Date(d.paidAt).toLocaleString());
  if (d.feeAmount != null) row("Fee", `${d.currency} ${Number(d.feeAmount).toLocaleString()}`);
  if (d.netAmount != null) row("Net", `${d.currency} ${Number(d.netAmount).toLocaleString()}`);

  y += 20;
  doc.setDrawColor(230).line(40, y, w - 40, y);
  y += 24;
  doc.setFont("helvetica", "normal").setFontSize(9).setTextColor(140);
  if (d.supportEmail) doc.text(`Support: ${d.supportEmail}`, 40, y);
  doc.text("Generated by PayNOC · paynoc.app", 40, y + 14);

  doc.save(`receipt-${d.invoiceNumber}.pdf`);
}
