# ---- PayNOC — Dockerfile for Coolify / any Docker host ----
# Builds a Node server (Nitro node-server preset) that serves SSR + APIs.
# Vite 8 must run on real Node 22, not Bun's Node-compat runtime, otherwise
# Coolify builds can fail with node:util/parseEnv-related errors.

FROM oven/bun:1.2.23-alpine AS bun

FROM node:22-alpine AS build
WORKDIR /app

RUN apk add --no-cache libstdc++
COPY --from=bun /usr/local/bin/bun /usr/local/bin/bun

COPY package.json bun.lock* bunfig.toml ./
RUN bun install --frozen-lockfile || bun install
COPY . .

# Public envs baked at build time. Only publishable/anon values are declared
# here — never SERVICE_ROLE_KEY or other private runtime-only secrets.
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_PUBLISHABLE_KEY
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPABASE_PROJECT_ID
ARG SUPABASE_URL
ARG SUPABASE_PUBLISHABLE_KEY
ARG SUPABASE_ANON_KEY
ARG SERVICE_URL_SUPABASEKONG
ARG SERVICE_URL_SUPABASEKONG_8000
ARG SERVICE_SUPABASEANON_KEY
ARG PAYNOC_SUPABASE_URL
ARG PAYNOC_SUPABASE_ANON_KEY
ARG PAYNOC_SUPABASE_PUBLISHABLE_KEY
ARG PAYNOC_SUPABASE_PROJECT_ID

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_PUBLISHABLE_KEY=$VITE_SUPABASE_PUBLISHABLE_KEY \
    VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY \
    VITE_SUPABASE_PROJECT_ID=$VITE_SUPABASE_PROJECT_ID \
    SUPABASE_URL=$SUPABASE_URL \
    SUPABASE_PUBLISHABLE_KEY=$SUPABASE_PUBLISHABLE_KEY \
    SUPABASE_ANON_KEY=$SUPABASE_ANON_KEY \
    SERVICE_URL_SUPABASEKONG=$SERVICE_URL_SUPABASEKONG \
    SERVICE_URL_SUPABASEKONG_8000=$SERVICE_URL_SUPABASEKONG_8000 \
    SERVICE_SUPABASEANON_KEY=$SERVICE_SUPABASEANON_KEY \
    PAYNOC_SUPABASE_URL=$PAYNOC_SUPABASE_URL \
    PAYNOC_SUPABASE_ANON_KEY=$PAYNOC_SUPABASE_ANON_KEY \
    PAYNOC_SUPABASE_PUBLISHABLE_KEY=$PAYNOC_SUPABASE_PUBLISHABLE_KEY \
    PAYNOC_SUPABASE_PROJECT_ID=$PAYNOC_SUPABASE_PROJECT_ID \
    PAYNOC_DOCKER_TARGET=node \
    NITRO_PRESET=node-server

RUN node ./node_modules/vite/bin/vite.js build

FROM node:22-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production PORT=3000
COPY --from=build /app/.output ./.output
EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]
