#!/bin/sh
# Resolve PayNOC backend aliases into the canonical env names used by Vite,
# the browser bundle, and TanStack server functions. POSIX sh keeps this safe
# for Docker/Coolify build and runtime.

first_non_empty() {
  for name in "$@"; do
    eval "value=\${$name:-}"
    if [ -n "$value" ]; then
      printf '%s' "$value"
      return 0
    fi
  done
  return 1
}

BACKEND_URL="$(first_non_empty \
  VITE_SUPABASE_URL \
  PAYNOC_PRODUCTION_SUPABASE_URL \
  PAYNOC_PROD_SUPABASE_URL \
  PAYNOC_SUPABASE_URL \
  SUPABASE_URL \
  SERVICE_URL_SUPABASEKONG \
  SERVICE_URL_SUPABASEKONG_8000 \
  || true)"

BACKEND_ANON_KEY="$(first_non_empty \
  VITE_SUPABASE_PUBLISHABLE_KEY \
  VITE_SUPABASE_ANON_KEY \
  PAYNOC_PRODUCTION_SUPABASE_PUBLISHABLE_KEY \
  PAYNOC_PRODUCTION_SUPABASE_ANON_KEY \
  PAYNOC_PROD_SUPABASE_PUBLISHABLE_KEY \
  PAYNOC_PROD_SUPABASE_ANON_KEY \
  PAYNOC_SUPABASE_PUBLISHABLE_KEY \
  PAYNOC_SUPABASE_ANON_KEY \
  SUPABASE_PUBLISHABLE_KEY \
  SUPABASE_ANON_KEY \
  SERVICE_SUPABASEANON_KEY \
  || true)"

BACKEND_SERVICE_KEY="$(first_non_empty \
  PAYNOC_PRODUCTION_SUPABASE_SERVICE_ROLE_KEY \
  PAYNOC_PROD_SUPABASE_SERVICE_ROLE_KEY \
  PAYNOC_SUPABASE_SERVICE_ROLE_KEY \
  SUPABASE_SERVICE_ROLE_KEY \
  SERVICE_SUPABASESERVICE_KEY \
  || true)"

BACKEND_JWT_SECRET="$(first_non_empty \
  PAYNOC_PRODUCTION_SUPABASE_JWT_SECRET \
  PAYNOC_PROD_SUPABASE_JWT_SECRET \
  PAYNOC_SUPABASE_JWT_SECRET \
  SUPABASE_JWT_SECRET \
  SERVICE_PASSWORD_JWT \
  JWT_SECRET \
  || true)"

BACKEND_PROJECT_ID="$(first_non_empty \
  VITE_SUPABASE_PROJECT_ID \
  PAYNOC_PRODUCTION_SUPABASE_PROJECT_ID \
  PAYNOC_PROD_SUPABASE_PROJECT_ID \
  PAYNOC_SUPABASE_PROJECT_ID \
  SUPABASE_PROJECT_ID \
  || true)"

export VITE_SUPABASE_URL="${VITE_SUPABASE_URL:-$BACKEND_URL}"
export SUPABASE_URL="${SUPABASE_URL:-$BACKEND_URL}"

export VITE_SUPABASE_PUBLISHABLE_KEY="${VITE_SUPABASE_PUBLISHABLE_KEY:-$BACKEND_ANON_KEY}"
export VITE_SUPABASE_ANON_KEY="${VITE_SUPABASE_ANON_KEY:-$BACKEND_ANON_KEY}"
export SUPABASE_PUBLISHABLE_KEY="${SUPABASE_PUBLISHABLE_KEY:-$BACKEND_ANON_KEY}"
export SUPABASE_ANON_KEY="${SUPABASE_ANON_KEY:-$BACKEND_ANON_KEY}"

if [ -n "$BACKEND_SERVICE_KEY" ]; then
  export SUPABASE_SERVICE_ROLE_KEY="${SUPABASE_SERVICE_ROLE_KEY:-$BACKEND_SERVICE_KEY}"
fi

if [ -n "$BACKEND_JWT_SECRET" ]; then
  export SUPABASE_JWT_SECRET="${SUPABASE_JWT_SECRET:-$BACKEND_JWT_SECRET}"
fi

export VITE_SUPABASE_PROJECT_ID="${VITE_SUPABASE_PROJECT_ID:-${BACKEND_PROJECT_ID:-paynoc}}"
export SUPABASE_PROJECT_ID="${SUPABASE_PROJECT_ID:-${BACKEND_PROJECT_ID:-paynoc}}"