// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DIRECT_BACKEND_OVERRIDE_KEY = 'paynoc-use-direct-backend';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function normalizeUrl(value: string | undefined) {
  return typeof value === 'string' ? value.replace(/\/+$/, '') : value;
}

function shouldUseSameOriginGateway(configuredUrl: string) {
  if (typeof window === 'undefined') return false;
  if (window.localStorage.getItem(DIRECT_BACKEND_OVERRIDE_KEY) === '1') return false;

  const host = window.location.hostname.toLowerCase();
  if (host === 'localhost' || host === '127.0.0.1' || host.endsWith('.lovable.app')) {
    return false;
  }

  try {
    const configuredHost = new URL(configuredUrl).hostname.toLowerCase();
    // Lovable Cloud's backend already allows the published/custom app domain
    // over CORS. Proxying it through /api/backend can fail when a self-hosted
    // internal gateway DNS value is present on the server, which breaks login.
    if (configuredHost.endsWith('.lovable.cloud')) return false;
    return configuredHost !== host;
  } catch {
    return false;
  }
}

function resolveSupabaseUrl(rawUrl: string | undefined) {
  const configuredUrl = normalizeUrl(rawUrl);
  if (!configuredUrl) return configuredUrl;

  // Production/self-hosted browsers should not be blocked by a separate
  // API gateway domain's DNS/CORS/SSL. The app exposes the same backend under
  // /api/backend/*, so auth/rest/storage calls stay same-origin.
  if (shouldUseSameOriginGateway(configuredUrl)) {
    return `${window.location.origin}/api/backend`;
  }

  return configuredUrl;
}

function createSupabaseClient() {
  // Direct connection to Supabase (same Coolify stack, same domain setup).
  // On self-hosted production, use a same-origin gateway fallback when the
  // configured API domain differs from the app domain.
  const rawUrl = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  // Strip trailing slash — a URL like https://db.paynoc.com/ makes supabase-js
  // build /auth/v1//token, which some Kong configs reject with a CORS-less 404.
  const SUPABASE_URL = resolveSupabaseUrl(rawUrl);
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;


  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }


  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

